{% set name = "aedat" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aedat-{{ version }}.tar.gz
  sha256: 33683279d8cd79add0bb3e2117fda32be71d546b403c4efcf6968b3a974ae4bd
  patches:
    - fix-cargo.patch

build:
  number: 3
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - numpy

test:
  imports:
    - aedat

about:
  home: https://github.com/neuromorphicsystems/aedat/
  summary: A fast AEDAT4 decoder with an underlying Rust implementation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
