{% set name = "aedat" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aedat-{{ version }}.tar.gz
  sha256: a2e2d36745863c85ef6723f6a7ab90ed972808f07f3dd7cd7f66d9d54cb527a0

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin
    - cargo-bundle-licenses
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - aedat

about:
  home: https://github.com/neuromorphicsystems/aedat/
  summary: A fast AEDAT4 decoder with an underlying Rust implementation
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - Tobias-Fischer
