{% set name = "aedat" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aedat-{{ version }}.tar.gz
  sha256: ee6b6ca4fceb079262da2ace54366b258687e5b0d85866f01cb7557281aaa40e

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - aedat

about:
  home: https://github.com/neuromorphicsystems/aedat/
  summary: A fast AEDAT4 decoder with an underlying Rust implementation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
