{% set name = "aedat" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aedat-{{ version }}.tar.gz
  sha256: c9c37288dc24787b1dfae50858b653b558f97a51ac8877290f8cac863dce545b

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin
    - cargo-bundle-licenses
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - aedat

about:
  home: https://github.com/neuromorphicsystems/aedat/
  summary: A fast AEDAT4 decoder with an underlying Rust implementation
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - Tobias-Fischer
